### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by adam0912s** [davidmashburn/SeedWaterSegmenter#2]
Hi, I'm using Windows Python 2.7 and I get the following error when I try the 'calculate' tool. Grateful for any feedback! Thanks.

Run Calculations!
Calculating for Frame 0
Get Values
Get Centroids
Get Bounds
Get Area
Get Perimeter
Get BF Ellipse
Get Neighbors
Traceback (most recent call last):
  File "C:\Users\adams\Anaconda2\lib\site-packages\SeedWaterSegmenter\SeedWaterSegmenter.py", line 3126, in RunCalculationsCallback
    self.wd.CollectAllStats(self.saveDir)
  File "C:\Users\adams\Anaconda2\lib\site-packages\SeedWaterSegmenter\SeedWaterSegmenter.py", line 1580, in CollectAllStats
    self.neighbors.append(self.CalculateNeighbors(boundsList=boundsList))
  File "C:\Users\adams\Anaconda2\lib\site-packages\SeedWaterSegmenter\SeedWaterSegmenter.py", line 1505, in CalculateNeighbors
    neighborPixels = (scipy.ndimage.binary_dilation(binary)-binary)*waterSmaller
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

**Comment by davidmashburn** [comment]
This should be fixed in version 0.6.5.1.
